
services:

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    ports: 
      - 11434:11434
    networks: 
      - proxy-net
    #network_mode: host
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    runtime: nvidia


  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    networks: 
      - proxy-net
    #network_mode: host
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3005:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - WEBUI_SECRET_KEY=$WEBUI_SECRET_KEY
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      caddy: ai.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  ollama: {}
  open-webui: {}

networks:
  proxy-net:
    name: proxy-net
    external: true
