include:
  - ~/docker/compose/shared-compose-head.yml

########################### SERVICES
services:

############################# FRONTENDS

  # Nginx Proxy Manager - Reverse Proxy with LetsEncrypt
  npm:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    # For Static IP
    networks:
    # For Static IP
      npm_proxy:
        ipv4_address: 192.168.89.254 # You can specify a static IP
    # For Dynamic IP
    # networks:
    #  - npm_proxy
    ports:
      - '80:80' # Public HTTP Port. Port Forwarding on Router is ON.
      - '443:443' # Public HTTPS Port. Port Forwarding on Router is ON.
      - '81:81' # Admin Web Port. Port Forwarding on Router is OFF. Internal Home Network Access only - 192.168.89.254:81.
    volumes:
      - $DOCKERDIR/appdata/npm/config:/config
      - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
      - $DOCKERDIR/appdata/npm/data:/data
    environment:
      DB_SQLITE_FILE: "/config/database.sqlite"
      DISABLE_IPV6: 'true'

########################## DOWNLOADERS

  # nzbget - Binary newsgrabber (NZB downloader)
  nzbget:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: jscottelblein/nzbget
    container_name: nzbget
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.216
    ports:
      - "6789:6789"
    volumes:
      - $DOCKERDIR/appdata/nzbget:/config
      - $DATADIR/downloads:/downloads
    environment:
      <<: *default-tz-puid-pgid

  # TransmissionBT - Torrent Downloader
  # transmission-openvpn:
  #     cap_add:
  #         - NET_ADMIN
  #     volumes:
  #         - $DATADIR/downloads/transmission:/data
  #         - $DOCKERDIR/appdata/transmission-openvpn:/config
  #         - $DOCKERDIR/privadovpn:/etc/openvpn/custom
  #     environment:
  #         OPENVPN_PROVIDER: custom
  #         OPENVPN_CONFIG: yvr-001
  #         OPENVPN_USERNAME: $PRIVADO_USERNAME
  #         OPENVPN_PASSWORD: $PRIVADO_PASSWORD
  #         LOCAL_NETWORK: 192.168.0.0/16
  #         TRANSMISSION_WEB_UI: combustion
  #     logging:
  #         driver: json-file
  #         options:
  #             max-size: 10m
  #     ports:
  #         - '9091:9091'
  #         - '61234:61234'
  #     image: haugene/transmission-openvpn

  # mam_cookie:
  #   image: alpine
  #   network_mode: "service:transmission"
  #   command: /bin/sh -c "apk add curl && apk add python3 && curl -c /mam.cookie -b 'mam_id=${MAM_ID}' https://t.myanonamouse.net/json/dynamicSeedbox.php | python3 -c \"import sys,json; sys.exit(not json.load(sys.stdin)['Success'])\""
  #   restart: "on-failure"

  transmission:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/transmission:4.0.4
    container_name: transmission
    environment:
      <<: *default-tz-puid-pgid
      #- TRANSMISSION_WEB_HOME= #optional
      USER: $TRANSMISSION_USER
      PASS: $TRANSMISSION_PASS
      #- WHITELIST= #optional
      #- PEERPORT= #optional
      #- HOST_WHITELIST= #optional
    volumes:
      - $DOCKERDIR/appdata/transmission:/config
      - $DATADIR/downloads/transmission:/downloads
      - $DATADIR/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp


########################## PVRs

  # Radarr - Movie management
  radarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:nightly # latest tag was causing "Error parsing column 45"
    container_name: radarr
    networks:
      npm_proxy:
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR/downloads:/downloads/
      - $DATADIR:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # Radarr 4K - Movie management
  radarr4k:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:nightly # latest tag was causing "Error parsing column 45"
    container_name: radarr4k
    networks:
      npm_proxy:
    ports:
      - "7879:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr4k:/config
      - $DATADIR/downloads:/downloads/
      - $DATADIR:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # Sonarr - TV Shows management
  sonarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.167
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR/downloads:/downloads
      - $DATADIR:/tv
      - $DATADIR/downloads/transmission/completed/tv-shows:/downloads/completed/tv-shows
      - $DATADIR/downloads/completed/Series:/downloads/completed/Series
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # Sonarr - TV Shows management
  sonarr-anime:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr-anime
    networks:
      npm_proxy:
    ports:
      - "8990:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr-anime:/config
      - $DATADIR/downloads:/downloads
      - $DATADIR:/tv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  jellyfin:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    user: 1000:1000
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR:/data/tvshows
      - $DATADIR:/data/movies
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    ports:
      - 8096:8096
    environment:
      #<<: *default-tz-puid-pgid
      NVIDIA_VISIBLE_DEVICES: all
      JELLYFIN_PublishedServerUrl: https://jellyfin.bradserver.dev
      JELLYFIN_DATA_DIR: /config/data
      JELLYFIN_CONFIG_DIR: /config
      JELLYFIN_LOG_DIR: /config/log
      JELLYFIN_CACHE_DIR: /config/cache
    runtime: nvidia


  # Recyclarr - handle trash-guides
  # recyclarr:
  #   <<: *common-keys-media # See EXTENSION FIELDS at the top
  #   image: ghcr.io/recyclarr/recyclarr:latest
  #   container_name: recyclarr
  #   volumes:
  #     - $DOCKERDIR/appdata/recyclarr:/config
  #   environment:
  #     <<: *default-tz-puid-pgid


  # Bazarr - Subtitle Management
#  bazarr:
#    <<: *common-keys-media # See EXTENSION FIELDS at the top
#    image: lscr.io/linuxserver/bazarr
#    container_name: bazarr
#    environment:
#      <<: *default-tz-puid-pgid
#    ports:
#      - "6767:6767"
#    volumes:
#      - $DOCKERDIR/appdata/bazarr:/config
#      - $DATADIR:/movies
#      - $DATADIR:/tv

  prowlarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
    ports:
      - 9696:9696

  unpackerr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - $DATADIR/downloads:/downloads
      - $DATADIR/downloads/transmission/completed/books:/downloads/completed/books

    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need.
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      <<: *default-tz-puid-pgid
      PUID: root
      PGID: root

      # Sonarr Config
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_API_KEY: $SONARR_API_KEY
      UN_SONARR_0_PATHS_0: /downloads
      UN_SONARR_0_PROTOCOLS: torrent,usenet
      UN_SONARR_0_TIMEOUT: 10s
      UN_SONARR_0_DELETE_ORIG: false
      UN_SONARR_0_DELETE_DELAY: 5m
      # Radarr Config
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_API_KEY: $RADARR_API_KEY
      UN_RADARR_0_PATHS_0: /downloads
      UN_RADARR_0_PROTOCOLS: torrent,usenet
      UN_RADARR_0_TIMEOUT: 10s
      UN_RADARR_0_DELETE_ORIG: false
      UN_RADARR_0_DELETE_DELAY: 5m
      # Readarr Config
      UN_READARR_0_URL: http://readarr:8787
      UN_READARR_0_API_KEY: $READARR_API_KEY
      UN_READARR_0_PATHS_0: /downloads
      UN_READARR_0_PROTOCOLS: torrent,usenet
      UN_READARR_0_TIMEOUT: 10s
      UN_READARR_0_DELETE_ORIG: false
      UN_READARR_0_DELETE_DELAY: 5m
      # # Folder Config
      # UN_FOLDER_0_PATH:
      # UN_FOLDER_0_EXTRACT_PATH:
      # UN_FOLDER_0_DELETE_AFTER: 10m
      # UN_FOLDER_0_DELETE_ORIGINAL: false
      # UN_FOLDER_0_DELETE_FILES: false
      # UN_FOLDER_0_MOVE_BACK: false
      # # Webhook Config
      # UN_WEBHOOK_0_URL:
      # UN_WEBHOOK_0_NAME:
      # UN_WEBHOOK_0_NICKNAME: Unpackerr
      # UN_WEBHOOK_0_CHANNEL:
      # UN_WEBHOOK_0_TIMEOUT: 10s
      # UN_WEBHOOK_0_SILENT: false
      # UN_WEBHOOK_0_IGNORE_SSL: false
      # UN_WEBHOOK_0_EXCLUDE_0:
      # UN_WEBHOOK_0_EVENTS_0: 0
      # UN_WEBHOOK_0_TEMPLATE_PATH:
      # UN_WEBHOOK_0_CONTENT_TYPE: application/json
      # # Command Hook Config
      # UN_CMDHOOK_0_COMMAND:
      # UN_CMDHOOK_0_NAME:
      # UN_CMDHOOK_0_TIMEOUT: 10s
      # UN_CMDHOOK_0_SILENT: false
      # UN_CMDHOOK_0_SHELL: false
      # UN_CMDHOOK_0_EXCLUDE_0:
      # UN_CMDHOOK_0_EVENTS_0: 0


#################### Books

  readarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: hotio/readarr:nightly
    container_name: readarr
    ports:
      - "8787:8787"
    volumes:
      - $DOCKERDIR/appdata/readarr:/config
      - '$DATADIR/ssd2tb/books:/config/Calibre Library'
      - $DATADIR/downloads/transmission/completed/books:/downloads/completed/books
      - $DATADIR/downloads/transmission:/downloads
      - $DATADIR/downloads/completed/eBooks:/downloads/completed/eBooks
      - $DATADIR/downloads/
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
      UMASK: 002
      #ARGS: ""

  readarr-audio:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: hotio/readarr:nightly
    container_name: readarr-audio
    ports:
      - "8788:8787"
    volumes:
      - $DOCKERDIR/appdata/readarr-audio:/config
      - $DATADIR/ssd2tb/audiobooks:/audiobooks
      - $DATADIR/media3/audiobooks:/audiobooks2
      - $DATADIR/downloads/transmission/completed/audiobooks:/downloads/completed/audiobooks
      - $DATADIR/downloads/completed/Audiobooks:/downloads/completed/Audiobooks
      - $DATADIR/downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
      UMASK: 002
      #ARGS: ""

  # lazylibrarian:
  #   <<: *common-keys-media # See EXTENSION FIELDS at the top
  #   image: lscr.io/linuxserver/lazylibrarian:latest
  #   container_name: lazylibrarian
  #   environment:
  #     <<: *default-tz-puid-pgid
  #     DOCKER_MODS: linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
  #   volumes:
  #     - $DOCKERDIR/appdata/lazylibrarian:/config
  #     - $DATADIR/downloads:/downloads
  #     - $DATADIR/ssd2tb/books:/books #optional
  #   ports:
  #     - 5299:5299
  #   restart: unless-stopped


  calibre:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      <<: *default-tz-puid-pgid
      CUSTOM_USER: $CALIBRE_USER
      PASSWORD: $CALIBRE_PASS
#      CLI_ARGS: #optional
    volumes:
      - '$DATADIR/ssd2tb/books:/config/Calibre Library'
      #- '$DOCKERDIR/appdata/calibre/Calibre Library:/config/Calibre Library'
      - $DOCKERDIR/appdata/calibre:/config
      - $DATADIR/calibreimport:/media/import
    ports:
      - 8380:8080
      - 8381:8081
#    restart: unless-stopped

  calibre-web:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    ports:
      - "8083:8083"
    volumes:
      - $DOCKERDIR/appdata/calibre-web:/config
      - $DATADIR/ssd2tb/books:/books
    environment:
      <<: *default-tz-puid-pgid
      #DOCKER_MODS: DOCKER_MODS=linuxserver/mods:universal-calibre
    #  OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional

  audiobookshelf:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "13378:80"
    volumes:
      - $DATADIR/ssd2tb/audiobooks:/audiobooks
      - $DATADIR/media3/audiobooks:/audiobooks2
      #- </path/to/podcasts>:/podcasts
      - $DOCKERDIR/appdata/audiobookshelf/config:/config
      - $DOCKERDIR/appdata/audiobookshelf/metadata:/metadata
    environment:
      <<: *default-tz-puid-pgid

