########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  default:
    driver: bridge
  # npm_proxy:
  #   name: npm_proxy
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.89.0/24
  proxy-net:
    name: proxy-net
    external: true

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  networks:
    - proxy-net
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  networks:
    - proxy-net
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  networks:
    - proxy-net
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
########################### SERVICES

services:

  # nzbget - Binary newsgrabber (NZB downloader)
  nzbget:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    networks:
      proxy-net:
        ipv4_address: 192.168.89.216
    ports:
      - "6789:6789"
    volumes:
      - $APPDATA/nzbget:/config
      - $SSDDOWNLOADDIR/queue:/downloads/queue
      - $SSDDOWNLOADDIR/intermediate:/downloads/intermediate
      - $SSDDOWNLOADDIR/nzb:/downloads/nzb
      - $SSDDOWNLOADDIR/tmp:/downloads/tmp
      - $SSDDOWNLOADDIR/scripts:/downloads/scripts
      - /home/brad/media/hdd8tb/downloads/completed:/downloads/completed
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: nzbget.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 6789}}"


  qbittorrent:
    #<<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      proxy-net:
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8091
      - TORRENTING_PORT=51413
    volumes:
      - $APPDATA/qbittorrent:/config
      - $DOWNLOADDIR/torrents:/downloads #optional
    ports:
      #- 8091:8080
      - 6881:6881
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
        caddy: torrent.bradserver.dev
        caddy.reverse_proxy: "{{upstreams 8091}}"
        #caddy.reverse_proxy: "192.168.0.5:8091"


########################## PVRs

  # Radarr - Movie management
  radarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:nightly # latest tag was causing "Error parsing column 45"
    container_name: radarr
    networks:
      proxy-net:
    ports:
      - "7878:7878"
    volumes:
      - $APPDATA/radarr:/config
      - $DOWNLOADDIR:/downloads/
      - $DATADIR:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: radarr.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 7878}}"

  # Radarr 4K - Movie management
  radarr4k:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:nightly # latest tag was causing "Error parsing column 45"
    container_name: radarr4k
    networks:
      proxy-net:
    ports:
      - "7879:7878"
    volumes:
      - $APPDATA/radarr4k:/config
      - $DOWNLOADDIR:/downloads/
      - $DATADIR:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: radarr4k.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 7878}}"

  # Sonarr - TV Shows management
  sonarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    networks:
      proxy-net:
        ipv4_address: 192.168.89.167
    ports:
      - "8989:8989"
    volumes:
      - $APPDATA/sonarr:/config
      - $DOWNLOADDIR:/downloads
      - $DATADIR:/tv
      - $DOWNLOADDIR/transmission/completed/tv-shows:/downloads/completed/tv-shows
      - $DOWNLOADDIR/completed/Series:/downloads/completed/Series
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: sonarr.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8989}}"

  sonarr-4K:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr-4K
    networks:
      proxy-net:
    ports:
      - "8991:8989"
    volumes:
      - $APPDATA/sonarr-4K:/config
      - $DOWNLOADDIR:/downloads
      - $DATADIR:/tv
      - $DOWNLOADDIR/completed/Series4K:/downloads/completed/Series4K
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: sonarr4k.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8989}}"

  # Sonarr - TV Shows management
  sonarr-anime:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr-anime
    networks:
      proxy-net:
    ports:
      - "8990:8989"
    volumes:
      - $APPDATA/sonarr-anime:/config
      - $DOWNLOADDIR:/downloads
      - $DATADIR:/tv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: sonarr-anime.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8989}}"


  # Recyclarr - handle trash-guides
  recyclarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    networks:
      proxy-net:
    volumes:
      - $APPDATA/recyclarr:/config
    environment:
      <<: *default-tz-puid-pgid

  # Bazarr - Subtitle Management
#  bazarr:
#    <<: *common-keys-media # See EXTENSION FIELDS at the top
#    image: lscr.io/linuxserver/bazarr
#    container_name: bazarr
#    environment:
#      <<: *default-tz-puid-pgid
#    ports:
#      - "6767:6767"
#    volumes:
#      - $DOCKERDIR/appdata/bazarr:/config
#      - $DATADIR:/movies
#      - $DATADIR:/tv

  prowlarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $APPDATA/prowlarr:/config
    ports:
      - 9696:9696
    labels:
      caddy: prowlarr.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 9696}}"      

  unpackerr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - $DOWNLOADDIR:/downloads
      - $DOWNLOADDIR/transmission/completed/books:/downloads/completed/books

    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need.
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      <<: *default-tz-puid-pgid

      # Sonarr Config
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_API_KEY: $SONARR_API_KEY
      UN_SONARR_0_PATHS_0: /downloads
      UN_SONARR_0_PROTOCOLS: torrent,usenet
      UN_SONARR_0_TIMEOUT: 10s
      UN_SONARR_0_DELETE_ORIG: false
      UN_SONARR_0_DELETE_DELAY: 5m
      # Radarr Config
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_API_KEY: $RADARR_API_KEY
      UN_RADARR_0_PATHS_0: /downloads
      UN_RADARR_0_PROTOCOLS: torrent,usenet
      UN_RADARR_0_TIMEOUT: 10s
      UN_RADARR_0_DELETE_ORIG: false
      UN_RADARR_0_DELETE_DELAY: 5m
      # Readarr Config
      UN_READARR_0_URL: http://readarr:8787
      UN_READARR_0_API_KEY: $READARR_API_KEY
      UN_READARR_0_PATHS_0: /downloads
      UN_READARR_0_PROTOCOLS: torrent,usenet
      UN_READARR_0_TIMEOUT: 10s
      UN_READARR_0_DELETE_ORIG: false
      UN_READARR_0_DELETE_DELAY: 5m
    ## Lidarr Settings
      # UN_LIDARR_0_URL: http://lidarr:8686
      # UN_LIDARR_0_API_KEY: $LIDARR_API_KEY
      # UN_LIDARR_0_PATHS_0: /downloads/torrents
      # UN_LIDARR_0_PROTOCOLS: torrent,usenet
      # UN_LIDARR_0_TIMEOUT: 10s
      # UN_LIDARR_0_DELETE_DELAY: 5m
      # UN_LIDARR_0_DELETE_ORIG: false
      # # Folder Config
      # UN_FOLDER_0_PATH:
      # UN_FOLDER_0_EXTRACT_PATH:
      # UN_FOLDER_0_DELETE_AFTER: 10m
      # UN_FOLDER_0_DELETE_ORIGINAL: false
      # UN_FOLDER_0_DELETE_FILES: false
      # UN_FOLDER_0_MOVE_BACK: false
      # # Webhook Config
      # UN_WEBHOOK_0_URL:
      # UN_WEBHOOK_0_NAME:
      # UN_WEBHOOK_0_NICKNAME: Unpackerr
      # UN_WEBHOOK_0_CHANNEL:
      # UN_WEBHOOK_0_TIMEOUT: 10s
      # UN_WEBHOOK_0_SILENT: false
      # UN_WEBHOOK_0_IGNORE_SSL: false
      # UN_WEBHOOK_0_EXCLUDE_0:
      # UN_WEBHOOK_0_EVENTS_0: 0
      # UN_WEBHOOK_0_TEMPLATE_PATH:
      # UN_WEBHOOK_0_CONTENT_TYPE: application/json
      # # Command Hook Config
      # UN_CMDHOOK_0_COMMAND:
      # UN_CMDHOOK_0_NAME:
      # UN_CMDHOOK_0_TIMEOUT: 10s
      # UN_CMDHOOK_0_SILENT: false
      # UN_CMDHOOK_0_SHELL: false
      # UN_CMDHOOK_0_EXCLUDE_0:
      # UN_CMDHOOK_0_EVENTS_0: 0


#################### Books

  bookshelf:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: ghcr.io/pennydreadful/bookshelf:softcover 
    container_name: bookshelf
    ports:
      - "8987:8787"
    volumes:
      - $APPDATA/bookshelf:/config
      - '$DATADIR/media3/books:/config/Calibre Library'
      #- $DOWNLOADDIR/torrents/completed/books:/downloads/completed/books
      - $DOWNLOADDIR/torrents:/downloads
      - $DOWNLOADDIR/completed/eBooks:/downloads/completed/eBooks
      - $DOWNLOADDIR/
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: readarr.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8787}}"

  bookshelf-audio:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: ghcr.io/pennydreadful/bookshelf:hardcover 
    container_name: bookshelf-audio
    ports:
      - "8988:8787"
    volumes:
      - $APPDATA/bookshelf-audio:/config
      - $DATADIR/hdd8tb/audiobooks:/audiobooks
      - $DOWNLOADDIR/torrents/completed/audiobooks:/downloads/completed/audiobooks
      - $DOWNLOADDIR/torrents/Audiobooks:/downloads/completed/Audiobooks
      - $DOWNLOADDIR/torrents:/downloads
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: readarr-audio.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8787}}"

  jellyfin:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    user: 1000:1000
    cpu_shares: 2000
    blkio_config:
      weight: 600
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /home/brad/jellyfin:/config
      - $DATADIR:/data/tvshows
      - $DATADIR:/data/movies
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    ports:
      - 8096:8096
    environment:
      #<<: *default-tz-puid-pgid
      NVIDIA_VISIBLE_DEVICES: all
      JELLYFIN_PublishedServerUrl: https://jellyfin.bradserver.dev
      JELLYFIN_DATA_DIR: /config/data
      JELLYFIN_CONFIG_DIR: /config
      JELLYFIN_LOG_DIR: /config/log
      JELLYFIN_CACHE_DIR: /config/cache
    runtime: nvidia
    labels:
      caddy: jellyfin.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8096}}"


  calibre:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      <<: *default-tz-puid-pgid
      CUSTOM_USER: $CALIBRE_USER
      PASSWORD: $CALIBRE_PASS
#      CLI_ARGS: #optional
    volumes:
      - '$DATADIR/media3/books:/config/Calibre Library'
      - "$DATADIR/media3/ttrpg-library:/config/TTRPG Library"
      #- '$DOCKERDIR/appdata/calibre/Calibre Library:/config/Calibre Library'
      - $APPDATA/calibre:/config
      - $DATADIR/calibreimport:/media/import
    ports:
      - 8380:8080
      - 8381:8081
#    restart: unless-stopped
    labels:
      caddy: calibre.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

  calibre-web:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: linuxserver/calibre-web:nightly
    container_name: calibre-web
    ports:
      - "8083:8083"
    volumes:
      - $APPDATA/calibre-web:/config
      - $DATADIR/media3/books:/books
    environment:
      <<: *default-tz-puid-pgid
      #DOCKER_MODS: DOCKER_MODS=linuxserver/mods:universal-calibre
    #  OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    labels:
      caddy: calibre-web.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8083}}"

  calibre-ttrpg:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: linuxserver/calibre-web:latest
    container_name: calibre-ttrpg
    ports:
      - "8084:8083"
    volumes:
      - $APPDATA/calibre-ttrpg:/config
      - "$DATADIR/media3/ttrpg-library:/books"
    environment:
      <<: *default-tz-puid-pgid
      #DOCKER_MODS: DOCKER_MODS=linuxserver/mods:universal-calibre
    #  OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    labels:
      caddy: ttrpg.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 8083}}"

#  audiobookrequest:
#    <<: *common-keys-core # See EXTENSION FIELDS at the top
#    container_name: audiobookrequest
#    image: markbeep/audiobookrequest:1
#    ports:
#      - '8000:5432'
#    volumes:
#      - $APPDATA/audiobookrequest:/config
#    environment:
#      <<: *default-tz-puid-pgid
#    #  ABR_APP__PORT: 5432
#    #  ABR_APP__OPENAPI_ENABLED: true
#    labels:
#      caddy: audiobookrequest.bradserver.dev
#      caddy.reverse_proxy: "{{upstreams 5432}}"


  audiobookshelf:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "13378:80"
    volumes:
      - $DATADIR/hdd8tb/audiobooks:/audiobooks
      #- </path/to/podcasts>:/podcasts
      - $APPDATAPERFORMANCE/audiobookshelf/config:/config
      - $APPDATAPERFORMANCE/audiobookshelf/metadata:/metadata
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: audiobooks.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

  wizarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
      - 5690:5690
    volumes:
      - $APPDATA/wizarr:/data    environment
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: wizarr.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 5690}}"

  jellyseerr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      <<: *default-tz-puid-pgid
    labels:
      caddy: requests.bradserver.dev
      caddy.reverse_proxy: "{{upstreams 5055}}"
    



volumes:
  rreading_glasses_data:
