########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228


services:
  core:
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Canada/Mountain
    restart: unless-stopped
    networks:
      - npm_proxy
    security_opt:
      - no-new-privileges:true

