services:
  cloveanddagger:
    container_name: cloveanddagger
    networks:
      - proxy-net
    ports:
      - 8883:5000
    image: swiftb3/cloveanddagger:latest
    restart: unless-stopped
    volumes:
      - $APPDATA/cloveanddagger/slaybellsring/clues:/app/wwwroot/slaybellsring/clues
    labels:
      caddy: cloveanddagger.ca, www.cloveanddagger.ca
      caddy.reverse_proxy: '{{upstreams 5000}}'
#   shop:
#     container_name: shop
#     networks:
#       - proxy-net
#     image: grandnode/grandnode2:latest
#     ports:
#       - 8580:8080
#       - 8543:443
#     volumes:
#       - $APPDATA/grandnode/app:/https:ro
#       - $APPDATA/grandnode/App_Data:/app/App_Data
#       - $APPDATA/grandnode/logs:/app/logs
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     depends_on:
#       - mongo
#     labels:
#       caddy: shop.cloveanddagger.ca
#       caddy.reverse_proxy: '{{upstreams 8080}}'
#   mongo:
#     container_name: mongo-db
#     image: mongo:latest
#     networks:
#       - proxy-net
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
#       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
#     volumes:
#       - dbdata6:/data/db
#     restart: unless-stopped
# 
# volumes:
#   dbdata6: null
networks:
  proxy-net:
    name: proxy-net
    external: true
