########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  npm_proxy:
    name: npm_proxy
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    ports:
      - "83:80"  # 80 to 82 already taken by other services
      # - "444:443" # 443 used by Nginx Proxy Manager. Disabled because we will put Heimdall behind proxy.
    volumes:
      - $APPDATA/heimdall:/config
    extends:
      file: /home/brad/docker/compose/shared-compose-head.yml
      service: core

  organizr:
    extends:
      file: /home/brad/docker/compose/shared-compose-head.yml
      service: core

    image: organizr/organizr:latest
    container_name: organizr
    volumes:
      - $APPDATA/organizr:/config
    ports:
      - "84:80"
      #BRANCH: "v2-master" #optional v2-master, master, v2-develop, develop, dev
      #FPM: false  #optional enable php to use the socket rather than TCP

  dozzle:
    extends:
      file: /home/brad/docker/compose/shared-compose-head.yml
      service: core

    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8081:8080"  # qBittorrent is using port 8080.
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 48h
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label.
      # DOCKER_HOST: tcp://socket-proxy:2375 # Use this instead if you have Socket Proxy enabled.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy and comment this line for improved security
      - $APPDATA/dozzle:/data

  filebrowser:
    extends:
      file: /home/brad/docker/compose/shared-compose-head.yml
      service: core

    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "82:80"  # 80 and 81 are used by Nginx Proxy Manager
    volumes:
      - $APPDATA/filebrowser:/config
      - $USERDIR:/srv

  portainer:
    extends:
      file: /home/brad/docker/compose/shared-compose-head.yml
      service: core
    image: portainer/portainer-ee:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - $APPDATA/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
